# Generated by Django 4.2.1 on 2023-06-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artista', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_artista', models.CharField(max_length=10)),
                ('nombre_artista', models.CharField(max_length=50)),
                ('apellido_artista', models.CharField(max_length=50)),
                ('edad_artista', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_Artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gcweb.artista')),
            ],
        ),
    ]
