# Generated by Django 4.2.1 on 2023-06-04 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_artista', models.CharField(max_length=10)),
                ('nombre_artista', models.CharField(max_length=50)),
                ('apellido_artista', models.CharField(max_length=50)),
                ('edad_artista', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='tipo_artista',
            old_name='apellido_artista',
            new_name='especialidad',
        ),
        migrations.RemoveField(
            model_name='tipo_artista',
            name='edad_artista',
        ),
        migrations.RemoveField(
            model_name='tipo_artista',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='tipo_artista',
            name='nombre_artista',
        ),
        migrations.RemoveField(
            model_name='tipo_artista',
            name='rut_artista',
        ),
        migrations.RemoveField(
            model_name='tipo_artista',
            name='tipo_Artista',
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.AddField(
            model_name='datos_artista',
            name='tipo_Artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gcweb.tipo_artista'),
        ),
    ]
