# Generated by Django 4.2.1 on 2023-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0003_rename_tipo_artista_datos_artista_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_artista',
            name='foto',
            field=models.ImageField(default='', upload_to='artista'),
        ),
    ]
