# Generated by Django 4.2.1 on 2023-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0004_datos_artista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_artista',
            name='foto',
            field=models.ImageField(null=True, upload_to='artista'),
        ),
    ]
