# Generated by Django 4.2.1 on 2023-06-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0005_alter_datos_artista_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('apellido_contacto', models.CharField(max_length=50)),
                ('correo_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.IntegerField()),
                ('tipo_contacto', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Sugerencia']])),
                ('mensaje_contacto', models.TextField()),
            ],
        ),
    ]
