# Generated by Django 4.2.1 on 2023-06-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0006_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artista', models.CharField(max_length=50)),
                ('descripcion_artista', models.CharField(max_length=200)),
                ('nombre_obra', models.CharField(max_length=50)),
                ('descripcion_obra', models.CharField(max_length=200)),
                ('tecnica_obra', models.CharField(max_length=50)),
                ('valor_obra', models.IntegerField()),
                ('imagen_obra', models.ImageField(null=True, upload_to='artista')),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='apellido_contacto',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_contacto',
        ),
    ]
