# Generated by Django 4.2.1 on 2023-06-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0007_publicacionart_remove_contacto_apellido_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionart',
            name='imagen_obra',
            field=models.ImageField(null=True, upload_to='obras'),
        ),
    ]
