# Generated by Django 4.2.1 on 2023-06-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0008_alter_publicacionart_imagen_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionart',
            name='imagen_obra',
            field=models.ImageField(null=True, upload_to='artista'),
        ),
    ]
