# Generated by Django 4.2.1 on 2023-06-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0009_alter_publicacionart_imagen_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_registro', models.CharField(max_length=20)),
                ('apellido_registro', models.CharField(max_length=20)),
                ('correo_registro', models.EmailField(max_length=50)),
                ('password_registro', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='publicacionart',
            name='valor_obra',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
