# Generated by Django 4.2.1 on 2023-06-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0010_registro_alter_publicacionart_valor_obra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='apellido_registro',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='password_registro',
            new_name='Contraseña',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='correo_registro',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='nombre_registro',
            new_name='Nombre',
        ),
    ]
