# Generated by Django 4.2.1 on 2023-06-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0012_alter_publicacionart_descripcion_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='tipos_contacto',
            field=models.IntegerField(choices=[[0, 'Consulta'], [1, 'Sugerencia']], default=1),
            preserve_default=False,
        ),
    ]
