# Generated by Django 4.2.1 on 2023-06-23 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gcweb', '0013_contacto_tipos_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='datos_artista',
            name='edad_artista',
        ),
        migrations.RemoveField(
            model_name='datos_artista',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='datos_artista',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='publicacionart',
            name='descripcion_artista',
        ),
        migrations.RemoveField(
            model_name='publicacionart',
            name='nombre_artista',
        ),
        migrations.AddField(
            model_name='datos_artista',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacionart',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gcweb.datos_artista'),
        ),
        migrations.DeleteModel(
            name='Tipo_artista',
        ),
        migrations.AddField(
            model_name='publicacionart',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gcweb.categoria'),
        ),
    ]
