# Generated by Django 4.2.1 on 2023-06-23 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0015_alter_publicacionart_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionart',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gcweb.categoria'),
        ),
    ]
