# Generated by Django 4.2.1 on 2023-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0018_delete_registro_remove_datos_artista_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_artista',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
