# Generated by Django 4.2.1 on 2023-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0019_datos_artista_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_artista',
            name='correo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
