# Generated by Django 4.2.1 on 2023-06-25 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gcweb', '0021_datos_artista_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_artista',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='publicacionart',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
