# Generated by Django 4.2.1 on 2023-06-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0023_publicacionart_mensaje_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionart',
            name='mensaje_rechazo',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
