# Generated by Django 4.2.1 on 2023-06-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0025_datos_artista_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_artista',
            old_name='usuario',
            new_name='usuarioCreadorDeCuenta',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipos_contacto',
            field=models.IntegerField(choices=[[0, 'Consulta'], [1, 'Sugerencia'], [2, 'Solicitar Creacion De cuenta']]),
        ),
    ]
