# Generated by Django 4.2.1 on 2023-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0026_rename_usuario_datos_artista_usuariocreadordecuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_postulante', models.CharField(max_length=50)),
                ('rut_postulante', models.CharField(max_length=10)),
                ('edad_postulante', models.IntegerField()),
                ('estado_civil_postulante', models.IntegerField(choices=[[0, 'Soltero'], [1, 'Casado'], [2, 'Separado'], [3, 'Divorciado'], [4, 'Viudo']], default=0)),
                ('antecedentes_postulante', models.TextField(max_length=200)),
                ('imagen_postulante', models.ImageField(null=True, upload_to='postulantes')),
                ('curriculum_postulante', models.FileField(null=True, upload_to='curriculum_postulante')),
            ],
        ),
    ]
