# Generated by Django 4.2.1 on 2023-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0027_postulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado_civil_postulante',
            field=models.IntegerField(choices=[[0, 'Seleccionar'], [1, 'Soltero'], [2, 'Casado'], [3, 'Separado'], [4, 'Divorciado'], [5, 'Viudo']], default=0),
        ),
    ]
