# Generated by Django 4.2.1 on 2023-07-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcweb', '0028_alter_postulacion_estado_civil_postulante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='antecedentes_postulante',
        ),
    ]
